// AUTO-GENERATED by ready-builder.ts
// Bu dosya script tarafından üretildi. El ile düzenlemeyin.
export const productsReady = [
  {
    "id": "202",
    "title": "KAŞE BEL VE KOL KUŞAKLI İÇ ASTARLI DÜĞME DETAY TRENÇ KAHVE",
    "price": 1499.99,
    "images": [
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/kase-bel-ve-kol-kusakli-ic-astarli-dugme-detay-trenc-kahve-87626147-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      },
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/kase-bel-ve-kol-kusakli-ic-astarli-dugme-detay-trenc-kahve-93579761-sw1200sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "203",
    "title": "KAŞE BEL VE KOL KUŞAKLI İÇ ASTARLI DÜĞME DETAY TRENÇ BORDO",
    "price": 1499.99,
    "images": [
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/kase-bel-ve-kol-kusakli-ic-astarli-dugme-detay-trenc-bordo-78479418-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      },
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/kase-bel-ve-kol-kusakli-ic-astarli-dugme-detay-trenc-bordo-86115976-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "204",
    "title": "DEGAJE YAKA BOYUN AKSESUAR DETAY UZUN ELBİSE SİYAH",
    "price": 899.99,
    "images": [
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGdEg4OG5hTHdQYmNFPQ/p/degaje-yaka-boyun-aksesuar-detay-uzun-sandy-elbise-siyah-24654253-sw1128sh1600.webp",
        "w": 100,
        "h": 140,
        "ar": 0.7143
      },
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGdEg4OG5hTHdQYmNFPQ/p/degaje-yaka-boyun-aksesuar-detay-uzun-sandy-elbise-siyah-38746099-sw1128sh1600.webp",
        "w": 100,
        "h": 140,
        "ar": 0.7143
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "205",
    "title": "BOYUNDAN BAĞLAMALI DANTEL İÇ ASTARLI UZUN ELBİSE SİYAH",
    "price": 699.99,
    "images": [
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGdEg4OG5hTHdQYmNFPQ/p/boyundan-baglamali-dantel-ic-astarli-uzun-elbise-siyah-49440889-sw1128sh1600.webp",
        "w": 100,
        "h": 140,
        "ar": 0.7143
      },
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGdEg4OG5hTHdQYmNFPQ/p/boyundan-baglamali-dantel-ic-astarli-uzun-elbise-siyah-23363478-sw1128sh1600.webp",
        "w": 100,
        "h": 140,
        "ar": 0.7143
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "206",
    "title": "KAŞE BEL VE KOL KUŞAKLI İÇ ASTARLI DÜĞME DETAY TRENÇ GRİ",
    "price": 1499.99,
    "images": [
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/kase-bel-ve-kol-kusakli-ic-astarli-dugme-detay-trenc-gri-82496580-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      },
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/kase-bel-ve-kol-kusakli-ic-astarli-dugme-detay-trenc-gri-53440836-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "207",
    "title": "KAŞE BEL VE KOL KUŞAKLI İÇ ASTARLI DÜĞME DETAY TRENÇ KREM",
    "price": 1499.99,
    "images": [
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/kase-bel-ve-kol-kusakli-ic-astarli-dugme-detay-trenc-krem-74614862-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      },
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/kase-bel-ve-kol-kusakli-ic-astarli-dugme-detay-trenc-krem-16422441-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "208",
    "title": "BEL VE KOL KEMER DETAY İÇ ASTARLI UZUN DERİ TRENÇ KAHVE 2035",
    "price": 1299.99,
    "images": [
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGdEg4OG5hTHdQYmNFPQ/p/belve-kol-kemer-detay-ic-astarli-uzun-deri-trenc-kahve-2035-68690029-sw1128sh1600.webp",
        "w": 100,
        "h": 140,
        "ar": 0.7143
      },
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGdEg4OG5hTHdQYmNFPQ/p/belve-kol-kemer-detay-ic-astarli-uzun-deri-trenc-kahve-2035-39945435-sw1128sh1600.webp",
        "w": 100,
        "h": 140,
        "ar": 0.7143
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "209",
    "title": "DEGAJE YAKA BOYUN AKSESUAR DETAY UZUN SANDY ELBİSE HAKİ",
    "price": 899.99,
    "images": [
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/degaje-yaka-boyun-aksesuar-detay-uzun-sandy-elbise-haki-82801420-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      },
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/degaje-yaka-boyun-aksesuar-detay-uzun-sandy-elbise-haki-58179730-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "210",
    "title": "BOYUNDAN BAĞLAMALI DANTEL İÇ ASTARLI UZUN ELBİSE BEYAZ",
    "price": 699.99,
    "images": [
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/boyundan-baglamali-dantel-ic-astarli-uzun-elbise-beyaz-27040998-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      },
      {
        "url": "https://cdn.qukasoft.com/f/728219/cG96WmFtNG0vcUp3ZUdGcEhzd25iN0FMYmNFPQ/p/boyundan-baglamali-dantel-ic-astarli-uzun-elbise-beyaz-77406827-sw1128sh1600.webp",
        "w": 513,
        "h": 684,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "901",
    "title": "Anvelop Beli Detaylı Saten Etek",
    "price": 1759,
    "images": [
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607162823_2009184217_0.jpg?v=1747131590",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      },
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607162823_2009184217_1.jpg?v=1747131590",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "903",
    "title": "Saten Midi Boy Yırtmaçlı Etek",
    "price": 1399,
    "images": [
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607135896_2009184217_0.jpg?v=1742414160",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      },
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607135896_2009184217_1.jpg?v=1742414160",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "904",
    "title": "Piton Desenli Cut Out Detaylı Saten Midi Etek",
    "price": 1839,
    "images": [
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607171894_2009184217_0.jpg?v=1742414169",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      },
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607171894_2009184217_1.jpg?v=1742414169",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "905",
    "title": "Parlak Dokulu Mini Etek",
    "price": 1929,
    "images": [
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607171993_2009184217_0.jpg?v=1742414177",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      },
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607171993_2009184217_1.jpg?v=1742414177",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "906",
    "title": "Logo Detaylı Etek",
    "price": 1759,
    "images": [
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607119216_2009184217_0.jpg?v=1742414166",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      },
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607119216_2009184217_1.jpg?v=1742414166",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "907",
    "title": "Asimetrik Kesim Gold Metal Fermuarlı Mini Etek",
    "price": 1669,
    "images": [
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607171986_2009184217_0.jpg?v=1742414167",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      },
      {
        "url": "https://statics-mp.boyner.com.tr/mnresize/520/-/Boynerimages/B2960607171986_2009184217_1.jpg?v=1742414167",
        "w": 520,
        "h": 712,
        "ar": 0.7303
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "A101",
    "title": "Medine ipeği 12 Sıra lastik Ferace",
    "price": 1499,
    "images": [
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/4e6cfe51-24f6-478b-b9b9-f36c46e1d947/3840/645ec273-7f3e-48c7-a895-48f881d2ba49.webp",
        "w": 1170,
        "h": 2080,
        "ar": 0.5625
      },
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/3ead9921-915d-4416-8d13-c7a557a0d45e/3840/190b6e19-cde1-4fd8-92b6-2df8db939d8e.webp",
        "w": 1170,
        "h": 2080,
        "ar": 0.5625
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "A102",
    "title": "Nubuk düğmeli yarasa panço",
    "price": 1299,
    "images": [
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/bae72c8e-014a-43a4-a282-603d931e7b47/3840/img-8548.webp",
        "w": 3024,
        "h": 4032,
        "ar": 0.75
      },
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/343a1721-ff1d-4fb4-a00e-ef106082e466/3840/img-8550.webp",
        "w": 3024,
        "h": 4032,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "A103",
    "title": "Medine İpek’i Şalı ile birleşik namaz feracesi",
    "price": 1599,
    "images": [
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/c58f9b4f-85a1-47b4-8f18-22ad97f975bd/3840/img-8475.webp",
        "w": 3021,
        "h": 3495,
        "ar": 0.8644
      },
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/578a2e3c-e723-4cea-8362-b6840f257b12/3840/img-8505.webp",
        "w": 2044,
        "h": 4029,
        "ar": 0.5073
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "A104",
    "title": "Medine İpeği Kumaş Pantolonlu Ferace Takımı 3 Parça",
    "price": 1899,
    "images": [
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/e8565b6a-e6b5-4d5b-bc00-29888b0531b0/3840/img-8685.webp",
        "w": 3024,
        "h": 4032,
        "ar": 0.75
      },
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/6cd17223-174d-41f4-90b4-c4b2a53f41ad/3840/img-8673.webp",
        "w": 3024,
        "h": 4032,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "A105",
    "title": "Model Esila Eteği Fırfırlı Ferce - Kiremit",
    "price": 1699,
    "images": [
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/e07e99c9-e821-4bd4-ad06-e540d9c3ed3c/3840/img-8116.webp",
        "w": 3024,
        "h": 3792,
        "ar": 0.7975
      },
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/f96a9aac-eda1-433c-b71d-ca940517754b/3840/img-8131.webp",
        "w": 3024,
        "h": 4032,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "E201",
    "title": "Mevlana Etek",
    "price": 1199,
    "images": [
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/a1d5d053-4163-47e2-8d84-4f18519147e0/3840/img-0927.webp",
        "w": 3024,
        "h": 3866,
        "ar": 0.7822
      },
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/b7bb4498-c36e-4005-b622-af2c8dee1b5f/3840/img-0928.webp",
        "w": 3024,
        "h": 3757,
        "ar": 0.8049
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "E202",
    "title": "Kışlık Kiloş Çift Taraflı Etek",
    "price": 1299,
    "images": [
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/b88d9dff-7eda-4426-9648-97c3c871c3fc/3840/img-8522.webp",
        "w": 3765,
        "h": 5647,
        "ar": 0.6667
      },
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/54184b17-8e40-4958-b578-e1f8dc6573d0/3840/img-8521.webp",
        "w": 3668,
        "h": 5501,
        "ar": 0.6668
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "E203",
    "title": "Büzgü Detaylı Astarlı Etek",
    "price": 1099,
    "images": [
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/c9b24bcb-fba7-4990-95a8-e3530e4b6717/3840/img-8487.webp",
        "w": 3690,
        "h": 5534,
        "ar": 0.6668
      },
      {
        "url": "https://cdn.myikas.com/images/fae7477a-2fd9-4329-810c-ce4447a45a99/665118dc-c5fc-41d1-bea2-407df00056cb/3840/img-8496.webp",
        "w": 3665,
        "h": 5498,
        "ar": 0.6666
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "6",
    "title": "Pileli Mini Etek",
    "price": 2079.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1713859890700.jpg?crop=center&height=1600&v=1742161290&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1705315083598.jpg?crop=center&height=1600&v=1742161290&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1705315091474.jpg?crop=center&height=1600&v=1742161290&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1705315100848.jpg?crop=center&height=1600&v=1742161290&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "7",
    "title": "Halter Askılı Sırt Fırfırlı Elbise",
    "price": 2694.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1740707197715.jpg?crop=center&height=1600&v=1742499463&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1741770626106.jpg?crop=center&height=1600&v=1742499463&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "8",
    "title": "Çiçek Nakışlı Tank Şort Takım",
    "price": 3678.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1715577080280.jpg?crop=center&height=1600&v=1742417116&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1715577072252.jpg?crop=center&height=1600&v=1742417116&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "9",
    "title": "Sırtı Açık Fırfırlı Şifon Midi Elbise",
    "price": 2325.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1722050028538_3477b5d5-a2b3-4b26-8f9e-5e05e5c9a1a1.jpg?crop=center&height=1600&v=1742334080&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1722050019264.jpg?crop=center&height=1600&v=1742334081&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1722050017743.jpg?crop=center&height=1600&v=1742334080&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "10",
    "title": "Rosemary Mavi Fırfırlı Mini Elbise",
    "price": 3162.21,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/RosemaryWhiteRuffleMiniDress-7_d340e9bd-0b4f-4254-9fb6-116a2c0802a7.webp?crop=center&height=2250&v=1743781504&width=1500",
        "w": 1500,
        "h": 2250,
        "ar": 0.6667
      },
      {
        "url": "https://siaora.com/cdn/shop/files/Rosemary-1.webp?crop=center&height=2250&v=1743781503&width=1500",
        "w": 1500,
        "h": 2250,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_001",
    "title": "Pileli Mini Etek",
    "price": 2079.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1713859890700.jpg?crop=center&height=1600&v=1742161290&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1705315083598.jpg?crop=center&height=1600&v=1742161290&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_002",
    "title": "Halter Askılı Sırt Fırfırlı Elbise",
    "price": 2694.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1740707197715.jpg?crop=center&height=1600&v=1742499463&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1741770626106.jpg?crop=center&height=1600&v=1742499463&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_003",
    "title": "Şık Kalp Yaka Dantel Detaylı Çiçekli Elbise",
    "price": 2694.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1737538531032_cb5bce35-7d8b-4abf-87cd-0cb84b7ee39b.jpg?crop=center&height=1600&v=1740256865&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1736739644665_60663333-6c6e-4de8-890b-e24d17326290.jpg?crop=center&height=1600&v=1740256865&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_004",
    "title": "Sırtı Açık Fırfırlı Şifon Midi Elbise",
    "price": 2325.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1722050028538.jpg?crop=center&height=1600&v=1742334080&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1722050019491.jpg?crop=center&height=1600&v=1742334080&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_005",
    "title": "Fırfırlı Uzun Kollu Dökümlü Siluetli Mini Elbise",
    "price": 2325.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/DSC-1144_8fcb588a-8505-47b1-b9ab-64fdaffe12ea.jpg?crop=center&height=2100&v=1741557088&width=1400",
        "w": 1400,
        "h": 2100,
        "ar": 0.6667
      },
      {
        "url": "https://siaora.com/cdn/shop/files/IMG-2671.jpg?crop=center&height=1321&v=1741557088&width=881",
        "w": 881,
        "h": 1321,
        "ar": 0.6669
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_101",
    "title": "Dreamers Midi Elbise",
    "price": 2571.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/KNOWN_BMB_BIANCA_BROWN_BASE_DRESS_115.jpg?crop=center&height=1600&v=1750729733&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/018A0969.jpg?crop=center&height=1600&v=1750729733&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_102",
    "title": "Işıltılı Yakalı Çiçek Desenli Dantel Mini Elbise - Mavi",
    "price": 3855.93,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/IMG-5596_e44699c9-2992-45d9-9dce-c0930cc31514.jpg?crop=center&height=1337&v=1750539011&width=892",
        "w": 892,
        "h": 1337,
        "ar": 0.6672
      },
      {
        "url": "https://siaora.com/cdn/shop/files/DSC-3591_ca25f64f-921b-44de-8916-5db455ee925c.jpg?crop=center&height=2100&v=1750539010&width=1400",
        "w": 1400,
        "h": 2100,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_103",
    "title": "Peplum Detaylı Çiçekli Romantik Mini Elbise",
    "price": 2817.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/sdd-13_1a25a0c0-37c4-473c-b543-64d3337a4033.jpg?crop=center&height=2100&v=1750453134&width=1400",
        "w": 1400,
        "h": 2100,
        "ar": 0.6667
      },
      {
        "url": "https://siaora.com/cdn/shop/files/sdd-12_9a5c1ca6-4fb9-49aa-be1a-139a94c5de33.jpg?crop=center&height=2100&v=1750453134&width=1400",
        "w": 1400,
        "h": 2100,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_104",
    "title": "Yandan Yırtmaçlı Drapeli Maksi Elbise",
    "price": 2694.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/c1.jpg?crop=center&height=2100&v=1750427393&width=1400",
        "w": 1400,
        "h": 2100,
        "ar": 0.6667
      },
      {
        "url": "https://siaora.com/cdn/shop/files/256_b5ee537f-2d09-4b0d-98e3-1637bbd0e6a3.jpg?crop=center&height=2100&v=1750427393&width=1400",
        "w": 1400,
        "h": 2100,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar_105",
    "title": "Metal Detaylı Pileli Kısa Elbise",
    "price": 2202.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1728558378085.jpg?crop=center&height=1600&v=1742161267&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      },
      {
        "url": "https://siaora.com/cdn/shop/files/B1728558377878.jpg?crop=center&height=1600&v=1742161267&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_001",
    "title": "Edwina V yakalı Örme Çiçekli Uzun Elbise",
    "price": 3074.99,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/edwina-v-neck-knitted-floral-maxi-dress-sd00707233166-beige-s-sunfere-669828_3d6fac3f-ef1d-42b7-93a2-317fc5c700c1.jpg?crop=center&height=1200&v=1745154276&width=800",
        "w": 800,
        "h": 1200,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_002",
    "title": "Sue Çiçek Baskılı Halter Yaka Uzun Sundress",
    "price": 2694.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/sue-floral-printed-halterneck-maxi-sundress-sd0020516107-orange-s-sunfere-865073_44a0f926-32d4-4fb1-8768-fa8f398f1d4e.jpg?crop=center&height=1600&v=1745155919&width=1067",
        "w": 1067,
        "h": 1600,
        "ar": 0.6669
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_003",
    "title": "Alva Çiçekli Örme Straplez Uzun Elbise",
    "price": 3935.99,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/alva-floral-knit-strapless-maxi-dress-sd00605132790-apricot-s-sunfere-858945_101629d7-046e-4874-977a-667e1d1dd270.jpg?crop=center&height=1200&v=1745155943&width=800",
        "w": 800,
        "h": 1200,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_004",
    "title": "Alexia Halterneck Floral-aplikeli Maxi Elbise",
    "price": 2817.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/alexia-halterneck-floral-applique-maxi-dress-sd00604122674-blue-s-sunfere-472970_904272e5-3946-49a8-805b-b006ff4bf372.jpg?crop=center&height=1199&v=1745270348&width=799",
        "w": 799,
        "h": 1199,
        "ar": 0.6664
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_005",
    "title": "Bej Renkli Nakışlı Çiongşam Qipao Mini Elbise",
    "price": 3554.7,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/75036618d6585d8484e0fe7bb8277dab_74e87ff5-f3a1-47ad-ac1c-c155254a125b.jpg?crop=center&height=1000&v=1743720674&width=750",
        "w": 750,
        "h": 1000,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_006",
    "title": "Button Ruched Long-Sleeve Gömlek",
    "price": 2729.37,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/fe37e372-3691-4469-9f04-b34267b37853.jpg?crop=center&height=1620&v=1743720710&width=1080",
        "w": 1080,
        "h": 1620,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_007",
    "title": "Çantalı Jakarlı A-Kesim Fırfırlı Kadın Midi Elbise",
    "price": 3186.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/55660063f0b873c61a8ad965f71c7d9b.jpg?crop=center&height=1000&v=1743720714&width=750",
        "w": 750,
        "h": 1000,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_008",
    "title": "Çiçek Desenli Balon Kol Elbise",
    "price": 3309.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/4dc2cda608d2baf0b374e4df578a3cf4.jpg?crop=center&height=1000&v=1743720732&width=750",
        "w": 750,
        "h": 1000,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_009",
    "title": "Emma Çiçekli Mini Elbise",
    "price": 3309.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/170036.jpg?crop=center&height=2250&v=1743878554&width=1500",
        "w": 1500,
        "h": 2250,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar3_010",
    "title": "Narin Fildişi Katmanlı Halter Midi Elbise",
    "price": 2817.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/IMG_0566.jpg?crop=center&height=5515&v=1742335476&width=3626",
        "w": 3626,
        "h": 5515,
        "ar": 0.6575
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_001",
    "title": "Ekose Desenli Önden Bağlamalı Spagetti Askılı Elbise",
    "price": 1833.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1737023706100.jpg?crop=center&height=1600&v=1740258253&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_002",
    "title": "Beyaz Çiçekli Dantel Spagetti Askılı Elbise",
    "price": 2694.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/IMG_0313.jpg?crop=center&height=5616&v=1742239971&width=3744",
        "w": 3744,
        "h": 5616,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_003",
    "title": "Nakış Detaylı Uzun Kollu Pamuklu Bluz",
    "price": 2202.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1723282500016.jpg?crop=center&height=1600&v=1742332048&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_004",
    "title": "Desenli Uzun Kollu V Yaka Maxi Elbise",
    "price": 2325.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1732531713350_4324cc4d-f9fa-41a8-990a-654678fbd7fb.jpg?crop=center&height=1600&v=1742333689&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_005",
    "title": "Dantelli Bedene Sahip Çiçek İşlemeli Midi Elbise",
    "price": 2817.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/IMG_0509.jpg?crop=center&height=5512&v=1742239879&width=3628",
        "w": 3628,
        "h": 5512,
        "ar": 0.6582
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_006",
    "title": "Omuzları Bağlamalı Çiçekli Dantelli Crop",
    "price": 1956.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1689315170624.jpg?crop=center&height=1600&v=1742235991&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_007",
    "title": "Büzgülü Arkası Açık Örgü Crop",
    "price": 1956.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/B1677145853879.jpg?crop=center&height=1600&v=1742235773&width=1200",
        "w": 1200,
        "h": 1600,
        "ar": 0.75
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_008",
    "title": "Sırt Fiyonk Detaylı Omuzları Açık Tulum",
    "price": 3063.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/SD2-287.jpg?crop=center&height=2100&v=1741987762&width=1400",
        "w": 1400,
        "h": 2100,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_009",
    "title": "Asimetrik Denim Yelek",
    "price": 2571.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/IMG_4269-Edit_e9ba950d-6a6b-430e-a783-3f1a0daaa0ee.jpg?crop=center&height=1833&v=1741972341&width=1222",
        "w": 1222,
        "h": 1833,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "sia_bahar4_010",
    "title": "Leopar Desenli Mini Etek",
    "price": 1956.81,
    "images": [
      {
        "url": "https://siaora.com/cdn/shop/files/Beschrijvingsafbeeldingen_17.jpg?crop=center&height=1063&v=1741487428&width=850",
        "w": 850,
        "h": 1063,
        "ar": 0.7996
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_001",
    "title": "Desenli V Yaka Askılı Crop Top Mor",
    "price": 1299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT380_1006_01.jpg?v=1748329323&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT380_1006_02.jpg?v=1748329323&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_002",
    "title": "Düğme Detaylı Askılı Bohem Bluz Bej",
    "price": 1599,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT378_1007_01.jpg?v=1748958504&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT378_1007_02.jpg?v=1748958504&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_003",
    "title": "Sırt Dekolteli Yazlık Bohem Elbise Mor - Kahverengi",
    "price": 1999,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR411_2038_01_76fe4a2e-5d8c-467f-9cfc-32628906c98b.jpg?v=1755607225&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR411_2038_02.jpg?v=1755607225&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_004",
    "title": "Kalın Askılı V Yakalı Uzun Tulum Kiremit",
    "price": 1999,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/MN056_1008_01.jpg?v=1755180255&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/MN056_1008_02.jpg?v=1755180255&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_005",
    "title": "Yandan Yırtmaçlı Beli Lastikli Bohem Midi Boy Etek Sarı",
    "price": 1349,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK166_1025_01.jpg?v=1745308019&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK166_1025_02.jpg?v=1745308019&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_006",
    "title": "Önden Katlamalı Şalvar Pantolon Bordo",
    "price": 1899,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT338_1013_01.jpg?v=1744729572&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT338_1013_02.jpg?v=1744729572&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_007",
    "title": "Yüksek Bel Geniş Paça Bohem Pantolon Mor",
    "price": 1899,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT353_1006_01.jpg?v=1744703002&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT353_1006_02.jpg?v=1744703002&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_008",
    "title": "Arkadan Bağlamalı Bohem Crop Bluz Siyah",
    "price": 1599,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT377_1005_01.jpg?v=1745308059&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT377_1005_02.jpg?v=1745308059&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_009",
    "title": "Beli Lastikli Desenli Yazlık Mini Şort Petrol",
    "price": 699,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT357_1022_01.jpg?v=1745308124&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT357_1022_02.jpg?v=1745308124&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_010",
    "title": "Kayık Yaka Oversize Yazlık Crop Bohem Bluz Siyah",
    "price": 1199,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LT345_1005_01.jpg?v=1741252442&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LT345_1005_02.jpg?v=1741252443&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_011",
    "title": "Bohem Desenli Volan Kollu Kısa Tulum Hardal",
    "price": 1199,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/MN057_1020_02.jpg?v=1753346585&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/MN057_1020_01.jpg?v=1753346585&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_012",
    "title": "Ayarlanabilir Askılı Bohem Müslin Elbise Siyah",
    "price": 2199,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR570_1005_02.jpg?v=1753346942&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR570_1005_01.jpg?v=1753346942&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_013",
    "title": "Bağlama Detaylı Bohem Mini Etek Çağla",
    "price": 1499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK168_1039_02.jpg?v=1753347088&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK168_1039_01.jpg?v=1753347088&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_014",
    "title": "Derin Yırtmaçlı Bohem Maxi Elbise Bordo",
    "price": 2199,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR538_1013_01.jpg?v=1744702717&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR538_1013_02.jpg?v=1744702717&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_015",
    "title": "Rahat Kesim Midi Boy Yazlık Bohem Etek Kiremit",
    "price": 2299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK170_1008_01.jpg?v=1745308071&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK170_1008_02.jpg?v=1745308071&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_016",
    "title": "Desenli V Yaka Önden Bağlamalı Mini Elbise Yeşil",
    "price": 1699,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR569_1003_01.jpg?v=1748329157&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR569_1003_02.jpg?v=1748329157&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_017",
    "title": "V Yaka Çiçek Desenli Crop Bluz Kırmızı",
    "price": 1299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT381_1004_01.jpg?v=1748329195&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT381_1004_02.jpg?v=1748329195&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_018",
    "title": "Desenli V Yaka Askılı Crop Top Mavi",
    "price": 1299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT380_1002_01.jpg?v=1748346519&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT380_1002_02.jpg?v=1748346519&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_019",
    "title": "Yan Yırtmaçlı Etnik Desenli Midi Bohem Elbise Yeşil",
    "price": 1999,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR564_1003_01.jpg?v=1748329122&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR564_1003_02.jpg?v=1748329122&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_020",
    "title": "Belden Bağlamalı Bol Paça Salaş Bohem Pantolon Bordo",
    "price": 799,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT352_1013_01.jpg?v=1744702958&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT352_1013_02.jpg?v=1744702958&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_021",
    "title": "Rahat Kesim Midi Boy Yazlık Bohem Etek Siyah",
    "price": 2299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK170_1005_01.jpg?v=1745308034&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK170_1005_02.jpg?v=1745308034&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_022",
    "title": "V Yakalı Askılı Yazlık Bohem Bluz Siyah",
    "price": 1279,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT382_1005_01.jpg?v=1744702770&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT382_1005_02.jpg?v=1744702770&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_023",
    "title": "Desenli V Yaka Askılı Crop Top Turkuaz",
    "price": 1299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT380_1024_01.jpg?v=1755606990&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT380_1024_02_daaa008b-3e2e-4a23-aad9-c2dd8fa46dd7.jpg?v=1755609009&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_024",
    "title": "Asimetrik Bohem Askılı Şık Midi Elbise Yeşil",
    "price": 1999,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR567_1003_01.jpg?v=1744702784&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR567_1003_02.jpg?v=1744702784&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_025",
    "title": "Rahat Kesim Yırtmaç Detaylı Etekli Bohem Pantolon Kiremit",
    "price": 1799,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT358_1008_01.jpg?v=1744703048&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT358_1008_02.jpg?v=1744703048&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_026",
    "title": "Kare Yaka Sırt Detaylı Bluz Beyaz",
    "price": 719,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT373_1001_01.jpg?v=1745307979&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT373_1001_02.jpg?v=1745307979&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_027",
    "title": "Belden Bağlamalı Bol Paça Salaş Bohem Pantolon Haki",
    "price": 1599,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT352_1015_01.jpg?v=1744702971&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT352_1015_02.jpg?v=1744702971&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_028",
    "title": "Asimetrik Bohem Askılı Şık Midi Elbise Kiremit",
    "price": 1999,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR567_1008_01.jpg?v=1744702811&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR567_1008_02.jpg?v=1744702811&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_029",
    "title": "Belden Bağlamalı Bol Paça Salaş Bohem Pantolon Siyah",
    "price": 1599,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT352_1005_03.jpg?v=1753346636&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT352_1005_02.jpg?v=1753346636&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_030",
    "title": "Yandan Düğmeli Etek Ucu Detaylı Yazlık Mini Etek Kiremit",
    "price": 799,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK169_1008_02.jpg?v=1753347268&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK169_1008_03.jpg?v=1744702904&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_031",
    "title": "V Yaka Minimal Askılı Bluz Siyah",
    "price": 1299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT375_1005_01.jpg?v=1745308274&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT375_1005_02.jpg?v=1745308274&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_032",
    "title": "Bohem Desenli Volan Kollu Kısa Tulum Mavi",
    "price": 999,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/MN057_1002_01.jpg?v=1750764398&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/MN057_1002_02.jpg?v=1750764398&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_033",
    "title": "Yüksek Bel Geniş Paça Bohem Pantolon Siyah",
    "price": 1899,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT353_1005_01.jpg?v=1744702986&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT353_1005_02.jpg?v=1744702986&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_034",
    "title": "V Yakalı Askılı Yazlık Bohem Bluz Kiremit",
    "price": 1279,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT382_1008_01.jpg?v=1744702917&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT382_1008_02.jpg?v=1744702917&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_035",
    "title": "Önden Düğüm Detaylı Kısa Tulum Sarı",
    "price": 839,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/MN053_1025_01.jpg?v=1737373416&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/MN053_1025_02.jpg?v=1737373416&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_036",
    "title": "İp Askılı Desenli Midi Boy Bohem Elbise Mor",
    "price": 1899,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/DR533_1006_01.jpg?v=1737374288&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/DR533_1006_02.jpg?v=1737374288&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_037",
    "title": "Bağlama Detaylı Bohem Mini Etek Siyah",
    "price": 1499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK168_1005_02.jpg?v=1753346525&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/SK168_1005_01.jpg?v=1753346525&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_038",
    "title": "V Yaka Çiçek Desenli Crop Bluz Hardal",
    "price": 1299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT381_1020_01.jpg?v=1748329233&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT381_1020_02.jpg?v=1748329233&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_039",
    "title": "Bohem Bağlamalı Bulmaca Pantolon Turkuaz",
    "price": 1799,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT327_1024_01.jpg?v=1741252416&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT327_1024_02.jpg?v=1741252417&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_040",
    "title": "Yan Yırtmaçlı Etnik Desenli Midi Bohem Elbise Sarı",
    "price": 1499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR564_1025_01.jpg?v=1748329140&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/DR564_1025_02.jpg?v=1748329140&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_041",
    "title": "Nakış Detaylı, Beyaz, Bohem Kadın Gömlek Beyaz",
    "price": 1559,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/PL002_1001_01.jpg?v=1737373653&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/PL002_1001_02.jpg?v=1737373654&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_042",
    "title": "Nakış Yaprak ve Çiçek İşlemeli Gömlek Beyaz",
    "price": 1599,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT365_1001_01.jpg?v=1737373218&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT365_1001_02.jpg?v=1737373218&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_043",
    "title": "Nakış Kuş İşlemeli Pamuklu Gömlek Beyaz",
    "price": 999,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT369_1001_01.jpg?v=1737373213&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT369_1001_02.jpg?v=1737373213&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_044",
    "title": "Dokulu Şık Saten Gömlek Beyaz",
    "price": 1499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT367_1001_01.jpg?v=1737373215&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT367_1001_02.jpg?v=1737373216&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_045",
    "title": "Saten Yüzeyli Desenli Gömlek Kahverengi",
    "price": 1399,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT366_1026_01.jpg?v=1737373217&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT366_1026_03.jpg?v=1737373217&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_046",
    "title": "V Yakalı Düşük Kollu Bohem Bluz Sarı",
    "price": 1499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT376_1025_01.jpg?v=1745308336&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT376_1025_02.jpg?v=1745308336&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_047",
    "title": "V Yakalı Askılı Yazlık Bohem Bluz Beyaz",
    "price": 895,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT382_1001_01.jpg?v=1744702743&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT382_1001_02.jpg?v=1744702743&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_048",
    "title": "V Yaka Minimal Askılı Bluz Bordo",
    "price": 1299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT375_1013_01.jpg?v=1745308290&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT375_1013_02.jpg?v=1745308290&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_049",
    "title": "Önü Kısa Arkası Uzun Fırfırlı Bohem Etek Pembe",
    "price": 499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/SK151_1023_01.jpg?v=1737373908&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/SK151_1023_02.jpg?v=1737373908&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_050",
    "title": "Belden Bağlamalı Bol Paça Salaş Bohem Pantolon Bordo",
    "price": 799,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT352_1013_01.jpg?v=1744702958&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT352_1013_02.jpg?v=1744702958&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_151",
    "title": "Leoplar Desenli Saten Gömlek Siyah - Gri",
    "price": 1549,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT368_2001_01.jpg?v=1737373214&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT368_2001_02.jpg?v=1737373214&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_152",
    "title": "Saten Yüzeyli Desenli Gömlek Kahverengi",
    "price": 1399,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT366_1026_01.jpg?v=1737373217&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LT366_1026_03.jpg?v=1737373217&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_153",
    "title": "Gizli Düğmeli Uzun Kollu Bohem Gömlek Haki",
    "price": 629,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LT339_1015_01.jpg?v=1737374253&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LT339_1015_02.jpg?v=1737374253&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_154",
    "title": "Bol Paça Pileli Salaş Etekli Pantolon Gül Kurusu",
    "price": 2199,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT359_1040_01.jpg?v=1744702850&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT359_1040_02.jpg?v=1744702850&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_155",
    "title": "Desenli Beli Gipeli Salaş Etekli Pantolon Sarı",
    "price": 1175,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT354_1025_01.jpg?v=1745308190&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      },
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT354_1025_02.jpg?v=1745308190&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_202",
    "title": "Uzun Kollu Desenli Bohem Kimono Mor",
    "price": 1499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LT349_1006_01.jpg?v=1741252452&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_203",
    "title": "Kısa Kollu Pamuklu Etnik Desenli Kimono Yeşil",
    "price": 449,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LT350_1003_01.jpg?v=1737374618&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_204",
    "title": "Kuşlu Bohem Panço Turuncu",
    "price": 1499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LC115_1021_01.jpg?v=1737374573&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_205",
    "title": "Balıksırtı Şık Kadın Takım Ceketi Gri",
    "price": 2499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LC128_1014_01.jpg?v=1737373184&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_206",
    "title": "Ekoseli Kruvaze Uzun Blazer Gri",
    "price": 2999,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LC127_1014_01.jpg?v=1737373219&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_207",
    "title": "Klasik Yaka Suni Deri Ceket Kahverengi",
    "price": 3499,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LC126_1026_01.jpg?v=1737373220&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_208",
    "title": "Blazer Kadın Ceket Beyaz",
    "price": 1299,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/LC108_1001_01.jpg?v=1737373850&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_209",
    "title": "Kapüşonlu Yüksek Yaka Kaban Siyah",
    "price": 1999,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LC111_1005_01.jpg?v=1737373841&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_210",
    "title": "Kapüşonlu Pamuklu Crop Sweatshirt Pembe",
    "price": 969,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LT357_1023_01.jpg?v=1737374190&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_211",
    "title": "Kapüşonlu Pamuklu Crop Sweatshirt Yeşil",
    "price": 969,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/LT357_1003_01.jpg?v=1737374241&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_212",
    "title": "Etnik Desenli Kapüşonlu Sweatshirt Lacivert",
    "price": 1399,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/MW017_1010_01.jpg?v=1737374353&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 2
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_213",
    "title": "Düğme Detaylı Düz Örgü Bohem Crop Hırka Bej",
    "price": 1699,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/KW036_1007_01.jpg?v=1737373247&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 3
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_214",
    "title": "Otantik Uzun Desenli Triko Panço Pembe",
    "price": 799,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/products/KW018_1023_01.jpg?v=1737374280&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 4
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_215",
    "title": "Yüksek Bel Geniş Paça Bohem Pantolon Siyah",
    "price": 1899,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT353_1005_01.jpg?v=1744702986&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 5
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  },
  {
    "id": "clan_kadin_216",
    "title": "Yüksek Bel Geniş Paça Bohem Pantolon Petrol - Bej - Siyah",
    "price": 1899,
    "images": [
      {
        "url": "https://clandestino.com.tr/cdn/shop/files/PT353_3003_01.jpg?v=1744703019&width=1200",
        "w": 1200,
        "h": 1800,
        "ar": 0.6667
      }
    ],
    "labels": {
      "tag": 1
    },
    "imagingStatus": "done",
    "taggingStatus": "done",
    "readyForSale": true
  }
] as const;
